### ISSUE TITLE
e and o for ɛ and ɔ as spellrelax rules

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-lin#2]
The changes to the lexicon in commit 4f87d95bc34f3598fe9f40b39f6c19b13a8042ec should be reversed, and e and o (and é and ó) variants of ɛ and ɔ (and ɛ́ and ɔ́) should be implemented as spellrelax rules instead.

**Comment by jonorthwash** [comment]
In fact, the spellrelax rules are already implemented; see [dev/spellrelax.twol](https://github.com/apertium/apertium-lin/blob/master/dev/spellrelax.twol).  Were they not working?

**Comment by jonorthwash** [comment]
@thefreezer, am I right in remembering that you reversed the changes you made regarding these characters?  If so, we can close this issue.

**Comment by thefreezer** [comment]
@jonorthwash yes, I already reversed the changes(fa56501882c10a975cc245130ccc2c024bab575a). So it can be closed.
